name: Karthik Ramasubbu
favicon: null
layout_spectrum: 0.45483722328208387
typography_spectrum: 0.7958258183207363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7983756153844297
  lightness: 0.8365580060053617
  saturation: 0.1774045149795711
  rhythmicContrast: 0.7283842656761408
purpose: []
